<script lang="ts">
	const components = [
		{ component: "Content Generator", what: "AI creates blog posts in your voice" },
		{ component: "Social Snippets", what: "AI extracts shareable quotes" },
		{ component: "Email Draft", what: "AI writes newsletter from your content" },
		{ component: "Content Dashboard", what: "See and manage all generated content" }
	];

	const weekShipped = [
		"AI workspace (CLAUDE.md + skills)",
		"Blog writer skill (reusable forever)",
		"Live website on Vercel",
		"User authentication",
		"Database with user data",
		"Core product feature",
		"AI-powered feature",
		"Content engine that generates for you",
		"2-minute demo"
	];
</script>

<svelte:head>
	<title>Day 5: Your AI Content Engine | code:zero</title>
	<meta name="description" content="Build a content machine that generates blog posts, social snippets, and emails. Demo Day Zero." />
	<link rel="preconnect" href="https://fonts.googleapis.com" />
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous" />
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
</svelte:head>

<nav class="navbar">
	<div class="nav-container">
		<a href="/learn/week-1" class="nav-back">
			<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
				<path d="M19 12H5M12 19l-7-7 7-7"/>
			</svg>
		</a>
		<span class="nav-title">Day 5: Your AI Content Engine</span>
		<div class="nav-spacer"></div>
	</div>
</nav>

<article class="lesson">
	<div class="container">
		<nav class="breadcrumb">
			<a href="/learn">Learn</a>
			<span class="sep">/</span>
			<a href="/learn/week-1">Week 1</a>
			<span class="sep">/</span>
			<span class="current">Day 5</span>
		</nav>

		<header class="lesson-header">
			<div class="day-badge">Day 5</div>
			<h1 class="lesson-title">Your AI Content Engine</h1>
			<p class="lesson-tagline">"Leave Week 1 with a machine that creates for you."</p>
		</header>

		<section class="content-section">
			<div class="challenge-card">
				<h2>The Challenge</h2>
				<p><strong>By end of day, you have an AI system that generates content for YOUR product.</strong></p>
				<p>Not one blog post. A SYSTEM. Blog posts, social snippets, email drafts—all generated by AI, all in your voice, all for your audience.</p>
				<p>This is the capstone. Everything you learned this week comes together.</p>
			</div>
		</section>

		<section class="content-section">
			<h2>What You're Building</h2>
			<div class="info-table">
				<div class="info-row header">
					<span>Component</span>
					<span>What It Does</span>
				</div>
				{#each components as item}
					<div class="info-row">
						<span>{item.component}</span>
						<span>{item.what}</span>
					</div>
				{/each}
			</div>
			<p><strong>By 4pm:</strong> You demo a working content engine to the intake.</p>
		</section>

		<section class="content-section">
			<h2>Morning: Build the Engine</h2>

			<h3>1. Architecture Planning (30 min)</h3>
			<div class="code-block prompt">
				<pre><code>You: I want to build an AI content engine for [my product].

It should:
1. Generate blog posts about topics in my niche
2. Create social media snippets from each post
3. Draft email newsletters
4. Store everything in my database
5. Let me review and edit before publishing

Help me plan the architecture. What tables do I need?
What AI functions? What UI components?</code></pre>
			</div>

			<h3>2. Build Content Generator (60 min)</h3>
			<div class="code-block prompt">
				<pre><code>You: Create a generateBlogPost function that:

1. Takes a topic as input
2. Reads CLAUDE.md for brand voice and audience info
3. Calls Gemini with a prompt that generates:
   - Attention-grabbing headline
   - Hook that identifies the problem
   - 3 main sections with actionable advice
   - Call-to-action relevant to [my product]
4. Returns markdown-formatted blog post
5. Targets 800-1200 words

The prompt should make the AI write like our brand.</code></pre>
			</div>

			<h3>3. Add Social + Email (75 min)</h3>
			<div class="code-block prompt">
				<pre><code>You: Create a generateSocialSnippets function that:

1. Takes a blog post as input
2. Extracts 5 shareable quotes/insights
3. Each snippet should be:
   - Under 280 characters (tweet-length)
   - Standalone (makes sense without context)
   - Intriguing (makes people want to read more)
4. Returns an array of 5 snippets</code></pre>
			</div>

			<div class="code-block prompt">
				<pre><code>You: Create a generateEmailDraft function that:

1. Takes a blog post as input
2. Creates a newsletter version that:
   - Has a compelling subject line
   - Opens with a personal hook
   - Summarizes the key insights (not the full post)
   - Includes a "Read the full post" CTA
3. Targets 200-300 words (email-appropriate length)</code></pre>
			</div>
		</section>

		<section class="content-section">
			<h2>Afternoon: Dashboard + Demo</h2>

			<h3>4. Content Dashboard (60 min)</h3>
			<div class="code-block prompt">
				<pre><code>You: Create a /content page for managing my content engine.

Include:
1. Topic input form
   - Text field for topic
   - "Generate Content" button
   - Loading state that shows progress

2. Content list
   - Show all generated content
   - Display topic, status, created date
   - Click to expand and see full content

3. Content detail view
   - Show blog post (rendered markdown)
   - Show social snippets (each in a card, with copy button)
   - Show email draft
   - Edit capability for each section

Match our brand styling.</code></pre>
			</div>

			<h3>5. Demo Day Zero (90 min)</h3>
			<div class="highlight-box">
				<strong>The 2-Minute Demo</strong>
				<p>Everyone presents their content engine live.</p>
			</div>

			<p><strong>Demo structure:</strong></p>
			<ol>
				<li><strong>Hook (15 sec):</strong> "Content creation takes forever. I built a machine."</li>
				<li><strong>Generate (60 sec):</strong> Live: Enter topic → watch AI create → show results</li>
				<li><strong>Output (30 sec):</strong> Show blog + snippets + email. "All from one click."</li>
				<li><strong>Close (15 sec):</strong> "Week 1: AI workspace to content engine."</li>
			</ol>

			<p><strong>Demo rules:</strong></p>
			<ul>
				<li>2 minutes MAX. Timer cuts you off.</li>
				<li>Live generation. Show the AI working in real-time.</li>
				<li>Your URL. Demo from your deployed site.</li>
				<li>Have backup. Pre-generated content if live fails.</li>
			</ul>
		</section>

		<section class="content-section">
			<h2>Week 1 Complete</h2>
			<div class="shipped-grid">
				{#each weekShipped as item}
					<div class="shipped-item">
						<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3">
							<polyline points="20 6 9 17 4 12"/>
						</svg>
						<span>{item}</span>
					</div>
				{/each}
			</div>
		</section>

		<section class="content-section">
			<div class="callout highlight">
				<h2>What's Different Now</h2>
				<ul>
					<li>You have a <strong>URL to share</strong></li>
					<li>You have a <strong>content machine running</strong></li>
					<li>You have <strong>skills you can reuse</strong></li>
					<li>You have <strong>momentum</strong></li>
				</ul>
				<p><em>By Friday, you'll have shipped more than most people ship in months. You'll have a product, users, and a content machine. All built WITH AI.</em></p>
			</div>
		</section>

		<section class="content-section">
			<div class="week2-preview">
				<h2>Week 2 Preview</h2>
				<p>What's coming:</p>
				<ul>
					<li>Day 6: Advanced database (joins, views, functions)</li>
					<li>Day 7: Complex UI patterns (modals, forms, validation)</li>
					<li>Day 8: File uploads and storage</li>
					<li>Day 9: Automation with n8n</li>
					<li>Day 10: Week 2 integration + Demo</li>
				</ul>
				<p><em>Week 2 starts Monday. You're no longer beginners. You're builders with systems.</em></p>
			</div>
		</section>

		<nav class="lesson-nav">
			<a href="/learn/week-1/day-4" class="nav-prev">
				<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
					<path d="M19 12H5M12 19l-7-7 7-7"/>
				</svg>
				Day 4: AI Does the Work
			</a>
			<a href="/learn/week-1" class="nav-next">
				Week 1 Overview
				<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
					<path d="M5 12h14M12 5l7 7-7 7"/>
				</svg>
			</a>
		</nav>
	</div>
</article>

<style>
	:global(:root) {
		--color-primary: #04A459;
		--gradient-accent: linear-gradient(135deg, #04A459 0%, #2ECC71 100%);
		--bg-base: #1a1d23;
		--bg-elevated: #242933;
		--bg-surface: #2e3440;
		--text-primary: #ffffff;
		--text-secondary: #a1a1a1;
		--text-muted: #6b7280;
		--border-subtle: #2e3440;
		--font-heading: 'Plus Jakarta Sans', system-ui, sans-serif;
		--font-body: 'Inter', system-ui, sans-serif;
		--font-mono: 'JetBrains Mono', monospace;
		--radius-sm: 4px; --radius-md: 8px; --radius-lg: 12px;
		--space-2: 0.5rem; --space-3: 0.75rem; --space-4: 1rem; --space-6: 1.5rem; --space-8: 2rem; --space-12: 3rem; --space-20: 5rem;
	}
	:global(*, *::before, *::after) { box-sizing: border-box; }
	:global(body) { margin: 0; font-family: var(--font-body); background: var(--bg-base); color: var(--text-secondary); line-height: 1.7; }
	.container { width: 100%; max-width: 800px; margin: 0 auto; padding: 0 var(--space-4); }
	.navbar { position: fixed; top: 0; left: 0; right: 0; z-index: 100; padding: var(--space-4) 0; background: rgba(26, 29, 35, 0.95); backdrop-filter: blur(12px); border-bottom: 1px solid var(--border-subtle); }
	.nav-container { position: relative; max-width: 1280px; margin: 0 auto; padding: 0 var(--space-4); display: flex; align-items: center; justify-content: space-between; }
	.nav-back { display: flex; align-items: center; justify-content: center; width: 40px; height: 40px; color: var(--text-secondary); text-decoration: none; border-radius: var(--radius-md); transition: color 150ms, background 150ms; }
	.nav-back:hover { color: var(--text-primary); background: var(--bg-hover); }
	.nav-title { position: absolute; left: 50%; transform: translateX(-50%); font-family: var(--font-heading); font-size: 0.875rem; font-weight: 600; color: var(--text-secondary); letter-spacing: 0.02em; white-space: nowrap; }
	.nav-spacer { width: 40px; }
	.lesson { padding: calc(var(--space-20) + 60px) 0 var(--space-20); }
	.breadcrumb { display: flex; align-items: center; gap: var(--space-2); font-size: 0.875rem; margin-bottom: var(--space-8); }
	.breadcrumb a { color: var(--text-muted); text-decoration: none; }
	.breadcrumb a:hover { color: var(--color-primary); }
	.breadcrumb .sep { color: var(--text-muted); }
	.breadcrumb .current { color: var(--text-secondary); }
	.lesson-header { margin-bottom: var(--space-12); padding-bottom: var(--space-8); border-bottom: 1px solid var(--border-subtle); }
	.day-badge { display: inline-block; padding: var(--space-2) var(--space-4); background: var(--gradient-accent); border-radius: var(--radius-md); font-size: 0.875rem; font-weight: 700; color: white; margin-bottom: var(--space-4); }
	.lesson-title { font-family: var(--font-heading); font-size: clamp(1.75rem, 5vw, 2.5rem); font-weight: 800; color: var(--text-primary); margin: 0 0 var(--space-3); line-height: 1.2; }
	.lesson-tagline { font-size: 1.125rem; font-style: italic; color: var(--text-secondary); margin: 0; }
	.content-section { margin-bottom: var(--space-12); }
	.content-section h2 { font-family: var(--font-heading); font-size: 1.5rem; font-weight: 700; color: var(--text-primary); margin: 0 0 var(--space-4); padding-top: var(--space-4); border-top: 1px solid var(--border-subtle); }
	.content-section h3 { font-family: var(--font-heading); font-size: 1.125rem; font-weight: 600; color: var(--text-primary); margin: var(--space-8) 0 var(--space-3); }
	.content-section p { margin: 0 0 var(--space-4); }
	.content-section ol, .content-section ul { margin: 0 0 var(--space-4); padding-left: var(--space-6); }
	.content-section li { margin-bottom: var(--space-2); }
	.challenge-card { background: linear-gradient(135deg, rgba(4, 164, 89, 0.1) 0%, rgba(4, 164, 89, 0.05) 100%); border: 1px solid rgba(4, 164, 89, 0.3); border-radius: var(--radius-lg); padding: var(--space-6); }
	.challenge-card h2 { border: none; padding-top: 0; margin-top: 0; }
	.code-block { background: var(--bg-elevated); border: 1px solid var(--border-subtle); border-radius: var(--radius-md); margin: var(--space-4) 0; }
	.code-block pre { margin: 0; padding: var(--space-4); overflow-x: auto; }
	.code-block code { font-family: var(--font-mono); font-size: 0.875rem; line-height: 1.6; color: var(--text-secondary); }
	.code-block.prompt { border-left: 3px solid var(--color-primary); }
	.code-block.prompt code { color: var(--text-primary); }
	.info-table { background: var(--bg-elevated); border: 1px solid var(--border-subtle); border-radius: var(--radius-md); overflow: hidden; margin: var(--space-4) 0; }
	.info-row { display: grid; grid-template-columns: 1fr 1fr; border-bottom: 1px solid var(--border-subtle); }
	.info-row:last-child { border-bottom: none; }
	.info-row.header span { font-weight: 600; color: var(--text-primary); background: var(--bg-surface); }
	.info-row span { padding: var(--space-3) var(--space-4); font-size: 0.875rem; }
	.info-row span:first-child { border-right: 1px solid var(--border-subtle); color: var(--text-muted); }
	.info-row span:last-child { color: var(--text-secondary); }
	.highlight-box { background: var(--gradient-accent); border-radius: var(--radius-lg); padding: var(--space-6); text-align: center; margin: var(--space-6) 0; }
	.highlight-box strong { display: block; font-family: var(--font-heading); font-size: 1.25rem; color: white; margin-bottom: var(--space-2); }
	.highlight-box p { color: rgba(255, 255, 255, 0.9); margin: 0; }
	.shipped-grid { display: grid; grid-template-columns: 1fr; gap: var(--space-2); background: var(--bg-elevated); border: 1px solid var(--border-subtle); border-radius: var(--radius-lg); padding: var(--space-4); }
	@media (min-width: 640px) { .shipped-grid { grid-template-columns: repeat(2, 1fr); } }
	.shipped-item { display: flex; align-items: center; gap: var(--space-3); padding: var(--space-2); }
	.shipped-item svg { color: var(--color-primary); flex-shrink: 0; }
	.shipped-item span { font-size: 0.9375rem; color: var(--text-secondary); }
	.callout.highlight { background: linear-gradient(135deg, rgba(4, 164, 89, 0.1) 0%, rgba(4, 164, 89, 0.05) 100%); border: 1px solid rgba(4, 164, 89, 0.3); border-left: 3px solid var(--color-primary); border-radius: var(--radius-md); padding: var(--space-4); }
	.callout.highlight h2 { border: none; padding-top: 0; margin-top: 0; font-size: 1.25rem; }
	.week2-preview { background: var(--bg-elevated); border: 1px solid var(--border-subtle); border-radius: var(--radius-lg); padding: var(--space-6); }
	.week2-preview h2 { border: none; padding-top: 0; margin-top: 0; }
	.lesson-nav { display: flex; justify-content: space-between; gap: var(--space-4); padding-top: var(--space-8); border-top: 1px solid var(--border-subtle); margin-top: var(--space-12); }
	.lesson-nav a { display: flex; align-items: center; gap: var(--space-2); padding: var(--space-4); background: var(--bg-elevated); border: 1px solid var(--border-subtle); border-radius: var(--radius-lg); text-decoration: none; color: var(--text-secondary); font-weight: 500; }
	.lesson-nav a:hover { border-color: var(--color-primary); color: var(--text-primary); }
	.nav-next { margin-left: auto; }
</style>
